commitSHA: "unknown"
ingress:
  domain: ""
observability:
  logging:
    level: info
    format: json
backend:
  acme:
    enabled: true
    extraArgs: []
    extraEnv:
      OTEL_SDK_DISABLED:
        value: "true"
      OTEL_LOG_LEVEL:
        value: info
    image:
      repository: ghcr.io/arikkfir/greenstar/backend-acme
      tag: "abc"
      pullPolicy: IfNotPresent
    postgres:
      connectTimeout: 1
    rbac:
      annotations: {}
    resources:
      limits:
        cpu: ""
        memory: ""
      requests:
        cpu: ""
        memory: ""
    volumeMounts: []
  migrate:
    enabled: true
    extraArgs: []
    extraEnv:
      OTEL_SDK_DISABLED:
        value: "true"
      OTEL_LOG_LEVEL:
        value: info
    image:
      repository: ghcr.io/arikkfir/greenstar/backend-migrate
      tag: "abc"
      pullPolicy: IfNotPresent
    postgres:
      connectTimeout: 1
    rbac:
      annotations: {}
    resources:
      limits:
        cpu: ""
        memory: ""
      requests:
        cpu: ""
        memory: ""
    volumeMounts: []
  server:
    extraArgs: []
    extraEnv:
      OTEL_SDK_DISABLED:
        value: "true"
      OTEL_LOG_LEVEL:
        value: info
    image:
      repository: ghcr.io/arikkfir/greenstar/backend-server
      tag: "abc"
      pullPolicy: IfNotPresent
    ingress:
      enabled: false
    postgres:
      connectTimeout: 1
    rbac:
      annotations: {}
    resources:
      limits:
        cpu: ""
        memory: ""
      requests:
        cpu: ""
        memory: ""
    volumeMounts: []
  volumes: []
frontend:
  extraArgs: []
  extraEnv: {}
  image:
    repository: ghcr.io/arikkfir/greenstar/frontend
    tag: "abc"
    pullPolicy: IfNotPresent
  ingress:
    enabled: false
  rbac:
    annotations: {}
  resources:
    limits:
      cpu: ""
      memory: ""
    requests:
      cpu: ""
      memory: ""
  volumeMounts: []
  volumes: []
  livenessProbe: true
  readinessProbe: true
  startupProbe: true
postgres:
  # Set backend user's password (defaults to random alphanumeric passwords)
  # NOTE: this is NOT updated on helm upgrade! to change, manually login to Postgres and update
  backendPassword: ""
  extraArgs: []
  extraEnv: {}
  extraUsers: {}
  ingress:
    enabled: false
  rbac:
    annotations: {}
  initPassword: ""
  resources:
    limits:
      cpu: ""
      memory: ""
    requests:
      cpu: ""
      memory: ""
  volumes: []
  volumeMounts: []
