// This file is generated by greenstar scripts. DO NOT EDIT.
// noinspection DuplicatedCode

import { DateProperties, Transaction } from "../../models/transaction.ts"
import { BaseAPIURL, QueryNilValue } from "../../services/util.ts"
import { Hook, Method, useOperation } from "../../util/operation.ts"

export interface Request {
    id: string
    currency?: string
}

export type Response = Transaction | undefined

function buildURL(req: Request): string {
    const urlParams = new URLSearchParams()
    if (req.currency !== undefined) {
        if (req.currency === null) {
            urlParams.set("currency", QueryNilValue)
        } else {
            urlParams.set("currency", req.currency)
        }
    }

    return `${BaseAPIURL}/transactions/${req.id}${urlParams.size ? "?" + urlParams.toString() : ""}`
}

export function useGetTransaction(): Hook<Request, Response> {
    const opts = {
        initial: undefined,
        method: "GET" as Method,
        url: buildURL,
        dateProperties: DateProperties,
    }
    return useOperation<Request, Response>(opts)
}
