# nonk8s
apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: greenstar
build:
  artifacts:
    - image: ghcr.io/arikkfir/greenstar/backend-acme
      context: backend
      docker:
        buildArgs:
          VERSION: v0.0.0+{{cmd "bash" "-c" "git rev-parse HEAD" | substr 0 7}}
        dockerfile: backend/Dockerfile.acme
        target: production
    - image: ghcr.io/arikkfir/greenstar/backend-migrate
      context: backend
      docker:
        buildArgs:
          VERSION: v0.0.0+{{cmd "bash" "-c" "git rev-parse HEAD" | substr 0 7}}
        dockerfile: backend/Dockerfile.migrate
        target: production
    - image: ghcr.io/arikkfir/greenstar/backend-server
      context: backend
      docker:
        buildArgs:
          VERSION: v0.0.0+{{cmd "bash" "-c" "git rev-parse HEAD" | substr 0 7}}
        dockerfile: backend/Dockerfile.server
        target: production
    - image: ghcr.io/arikkfir/greenstar/frontend
      context: frontend
      docker:
        buildArgs:
          VERSION: v0.0.0+{{cmd "bash" "-c" "git rev-parse HEAD" | substr 0 7}}
        dockerfile: frontend/Dockerfile
        target: development
      sync:
        manual:
          - src: src/**
            dest: /app/
  local:
    push: false
    useBuildkit: true
    concurrency: 1
deploy:
  helm:
    releases:
      - name: greenstar
        chartPath: ./deploy/chart
        packaged:
          appVersion: 0.0.0-{{cmd "bash" "-c" "git rev-parse HEAD" | substr 0 7}}
        namespace: greenstar
        createNamespace: true
        wait: true
        upgradeOnChange: true
        valuesFiles:
          - deploy/local/chart-local-values.yaml
          - hack/greenstar-values.yaml
        setValueTemplates:
          backend:
            acme:
              image:
                repository: "{{.IMAGE_REPO_ghcr_io_arikkfir_greenstar_backend_acme}}"
                tag: "{{.IMAGE_TAG_ghcr_io_arikkfir_greenstar_backend_acme}}@{{.IMAGE_DIGEST_ghcr_io_arikkfir_greenstar_backend_acme}}"
            migrate:
              image:
                repository: "{{.IMAGE_REPO_ghcr_io_arikkfir_greenstar_backend_migrate}}"
                tag: "{{.IMAGE_TAG_ghcr_io_arikkfir_greenstar_backend_migrate}}@{{.IMAGE_DIGEST_ghcr_io_arikkfir_greenstar_backend_migrate}}"
            server:
              image:
                repository: "{{.IMAGE_REPO_ghcr_io_arikkfir_greenstar_backend_server}}"
                tag: "{{.IMAGE_TAG_ghcr_io_arikkfir_greenstar_backend_server}}@{{.IMAGE_DIGEST_ghcr_io_arikkfir_greenstar_backend_server}}"
          frontend:
            image:
              repository: "{{.IMAGE_REPO_ghcr_io_arikkfir_greenstar_frontend}}"
              tag: "{{.IMAGE_TAG_ghcr_io_arikkfir_greenstar_frontend}}@{{.IMAGE_DIGEST_ghcr_io_arikkfir_greenstar_frontend}}"
