observability:
  logging:
    level: trace

ingress:
  domain: greenstar.test

backend:
  acme:
    extraEnv:
      OTEL_SDK_DISABLED:
        value: "true"
      OTEL_LOG_LEVEL:
        value: info
  migrate:
    extraEnv:
      OTEL_SDK_DISABLED:
        value: "true"
      OTEL_LOG_LEVEL:
        value: info
  server:
    extraEnv:
      OTEL_SDK_DISABLED:
        value: "true"
      OTEL_LOG_LEVEL:
        value: info
    ingress:
      enabled: true
      parentRef:
        kind: Gateway
        name: local
        namespace: ingress
        httpSectionName: web
        httpsSectionName: websecure

frontend:
  ingress:
    enabled: true
    parentRef:
      kind: Gateway
      name: local
      namespace: ingress
      httpSectionName: web
      httpsSectionName: websecure

postgres:
  backendPassword: "local"
  extraArgs:
    - -c
    - log_statement=mod
  extraUsers:
    local: local
  ingress:
    enabled: true
    parentRef:
      kind: Gateway
      name: local
      namespace: ingress
      tlsSectionName: postgres
  volumeMounts:
    - name: rates
      mountPath: /var/greenstar/rates
  volumes:
    - name: rates
      hostPath:
        path: /var/greenstar/rates
        type: Directory
