// This file is generated by greenstar scripts. DO NOT EDIT.
// noinspection DuplicatedCode

import { BaseAPIURL } from "../../services/util.ts"
import { Account, DateProperties } from "../../models/account.ts"
import { Hook, Method, useOperation } from "../../util/operation.ts"

export interface Request {
    id: string
    displayName?: string
    icon?: string
    parentID?: string
}

export type Response = Account | undefined

export function usePatchAccount(): Hook<Request, Response> {
    const opts = {
        initial: undefined,
        method: "PATCH" as Method,
        url: (req: Request) => `${BaseAPIURL}/accounts/${req.id}`,
        dateProperties: DateProperties,
    }
    return useOperation<Request, Response>(opts)
}
